cameras:
  - id: 1
    name: "Yard"
    url: "rtsp://10.0.0.192/h264_stream"
  - id: 2
    name: "Back Door"
    url: "rtsp://admin:admin1@10.0.0.153:554/h264Preview_01_main"
  - id: 3
    name: "Front Door"
    url: "rtsp://:@10.0.0.218/h264_stream"
